# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My website'
copyright: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://www.motoplanete.com/yamaha/zoom-700px/Yamaha-900-Tracer-2019-700px.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://blog.planete-yam.com/wp-content/uploads/2017/04/2016-Yamaha-XSR900-e1492202953642.jpg"
